### ISSUE TITLE
Tofu on non-latin characters

### ISSUE THREAD

**Issue by utybo** [utybo/BST#12]
Expected output (from https://ar.lipsum.com)

![image](https://user-images.githubusercontent.com/5175705/37876612-4f6d5692-304f-11e8-8776-662f1254670c.png)

Actual output (from OpenBST)

![image](https://user-images.githubusercontent.com/5175705/37876619-6a8a9e94-304f-11e8-83b9-2837d1b7c1b1.png)

***

Fix Roadmap

- [x] Add Missing Language dialog
- [x] Automatically switch to a compatible font unless `font` tag is present
- [x] Make it compatible with the XBF module

**Comment by utybo** [comment]
The source of the issue is that OpenBST forces use of either the Libre Baskerville font or the Ubuntu font. These only work for Latin characters. One way to work around this would be to either : 

* automatically detect if there is a non-latin character and force the sans-serif font (default system font which always works)
* provide a custom switch to be applied in the file. This isn't great as it would break out-of-the-box compatibility and require extra work.

What I'm thinking about here is to mix the two. OpenBST should automatically check for non-latin characters and, if it detects any, switch to sans-serif, or, if a custom font is specified, force the custom font no matter what and warn the user that some characters may be displayed incorrectly.

**Comment by utybo** [comment]
Fixed in b426680bf8a147851f4eefe7f1a12e06556b122d

**Comment by qwani** [comment]
thanks very much , really great great job
